### ISSUE TITLE
Can't resolve IConnectionManager

### ISSUE THREAD

**Issue by cecilphillip** [autofac/Autofac.SignalR#2]
I'm trying to resolve an IConnectionManager via constructor injection, but the resolution keeps failing. This is the only constructor in my class.

``` csharp
        public ChatEvaluator(IConnectionManager connectionManager)
        {
            _connectionManager = connectionManager;
            _context = GlobalHost.ConnectionManager.GetHubContext("RulesHub"); //this one works
        }
```

**_It's registered as follows**_

``` csharp
 builder.RegisterType(typeof(ChatEvaluator)).AsSelf().As<IEvaluation>().InstancePerDependency();
 builder.RegisterHubs(currentAssembly);

 var container = builder.Build(); 
 GlobalHost.DependencyResolver = new Autofac.Integration.SignalR.AutofacDependencyResolver(container);
```

**_Below is the error I receive:**_
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'TKM.AnalyticsEngine.Logic.ChatEvaluator' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.AspNet.SignalR.Infrastructure.IConnectionManager connectionManager' of constructor 'Void .ctor(Microsoft.AspNet.SignalR.Infrastructure.IConnectionManager)'."}

If I remove the parameter from the constructor, it works fine via GlobalHost.
I'm using autofac 3.5.2 and SignalR.Core 2.2.0 

Am I missing something ?

**Comment by tillig** [comment]
Looking through the Autofac SignalR integration code, I don't see anything that registers `IConnectionManager` automatically for you anywhere. There's only a `RegisterHubs` extension method and an `AutofacDependencyResolver` implementation.

Where do you register `IConnectionManager` in your application?

**Comment by cecilphillip** [comment]
It's a default signalR service that's a part of the DefaultDependencyResolver https://goo.gl/WcCRGp. It was my understanding that the Autofac resolver derived from it, so it should be able to resolve it no ?

**Comment by tillig** [comment]
That is true, but the Autofac resolver only passes to the base resolver if you directly call `GetService`. If you're resolving something from the container, all the dependencies must be in the container - it won't call out of the container into the `AutofacDependencyResolver` to get dependencies. Circular reference problem, right?

I think to get what you want, the `AutofacDependencyResolver` would need to override `Register` and somehow update the container with the registrations. That currently is not in place.

**Comment by cecilphillip** [comment]
Moved forward with resolving IHubContext instead for now
