### ISSUE TITLE
Constructor for AutofacDependencyResolver takes in an ILifetimeScope, examples (and tests..) pass in IContainer

### ISSUE THREAD

**Issue by chazt3n** [autofac/Autofac.SignalR#6]
I'm trying to use the signalr integration and I'm unable to understand how to use it as all examples pass in an IContainer - when using it this causes an exception. 

How do I _really_ use it?

**Comment by tillig** [comment]
So you [read the docs](http://autofac.readthedocs.io/en/latest/integration/signalr.html) and something isn't working? The docs show "how to really use it" so you're going to need to be way more specific.

I would recommend asking "how to" questions on StackOverflow and tag both `signalr` and `autofac`. There's a much larger audience there to help, and the Autofac maintainers follow there, too. When you do, paste a link in this issue so everyone can follow.

If you find a reproducible bug, that's a great issue - explain in detail with minimal repro steps, exception info, etc. what's up and then we can take a closer look.

**Comment by tillig** [comment]
Also, `IContainer` is an `ILifetimeScope` so passing that on during construction should absolutely work.

**Comment by chazt3n** [comment]
For me it does not work and I agree it should! That's bizarre, I'll ask there with code snippets so we can discover what I'm doing wrong. I did not know that an IContainer was also an ILifetimeScope, I must have some type of version mismatch or some other wonkiness.

P.S. Autofac is an amazing product, and it's an honor to have support directly from an owner.
